# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_auto_20171008_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_place',
            field=models.CharField(max_length=50),
        ),
    ]
