# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0004_auto_20171012_1308'),
        ('app_profile', '0002_auto_20171012_0042'),
    ]

    operations = [
    ]
