# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_friend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='middle_name',
        ),
    ]
