# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_friend', '0002_auto_20171009_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
