# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
